### ISSUE TITLE
Issue 1 : Update Markdown Files

### ISSUE THREAD

**Issue by Lakshya-GG** [Lakshya-GG/JavaScript-Games#1]
Issue Type: Task

Description:
This issue is a request for updating the existing Markdown (.md) files in the repository. As part of ongoing maintenance and improvement, it's essential to ensure that our documentation and other Markdown files are up-to-date and accurate.

Tasks:

- Review existing Markdown files to identify outdated content, broken links, or any inaccuracies.

- Update the Markdown files as necessary to reflect the latest information, changes, and improvements in the project.

- Ensure consistency in formatting, style, and naming conventions across all Markdown files.

Additional Information:
Please make sure to follow the best practices for Markdown file updates and provide a brief summary of the changes made in your pull request. If you encounter any issues or need clarification on specific content, feel free to ask for help or guidance in the comments section. Your contributions to keeping our documentation accurate and reliable are greatly appreciated!

**Comment by himanshunanda22** [comment]
@Lakshya-GG please assign this task to me.

**Comment by Lakshya-GG** [comment]
Issue Assigned @himanshunanda22
